/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import implementaciones.PersonaDAO;
import interfaces.IPersonaDAO;
import interfaz.ConsultaLicencia;
import interfaz.ConsultaPersona;
import interfaz.ConsultaPersonaTramite;
import interfaz.ConsultaPlaca;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import javax.swing.JButton;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Jesus
 */
public class Aplicacion extends javax.swing.JFrame {

    private final IPersonaDAO a = new PersonaDAO();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Aplicacion.class.getName());

    /**
     * Creates new form Aplicacion
     */
    public Aplicacion() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnModuloPlacas = new javax.swing.JButton();
        btnModuloLicencia = new javax.swing.JButton();
        btnModuloReportes = new javax.swing.JButton();
        btnPersonas = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnModuloConsultas = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModuloPlacas.setBackground(new java.awt.Color(168, 51, 99));
        btnModuloPlacas.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        btnModuloPlacas.setText("Modulo de placas");
        btnModuloPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloPlacasActionPerformed(evt);
            }
        });
        getContentPane().add(btnModuloPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 190, 70));

        btnModuloLicencia.setBackground(new java.awt.Color(168, 51, 99));
        btnModuloLicencia.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        btnModuloLicencia.setText("Modulo de licencias");
        btnModuloLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloLicenciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnModuloLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 180, 70));

        btnModuloReportes.setBackground(new java.awt.Color(168, 51, 99));
        btnModuloReportes.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        btnModuloReportes.setText("Modulo de reportes");
        btnModuloReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloReportesActionPerformed(evt);
            }
        });
        getContentPane().add(btnModuloReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 610, 190, 70));

        btnPersonas.setBackground(new java.awt.Color(168, 51, 99));
        btnPersonas.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        btnPersonas.setText("Insercion masiva");
        btnPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonasActionPerformed(evt);
            }
        });
        getContentPane().add(btnPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 610, 190, 70));

        jButton2.setText("jButton1");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 150, 70));

        btnModuloConsultas.setBackground(new java.awt.Color(168, 51, 99));
        btnModuloConsultas.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        btnModuloConsultas.setText("Modulo de consultas");
        btnModuloConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(btnModuloConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 180, 70));

        jButton3.setText("jButton1");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 150, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Menu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModuloPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloPlacasActionPerformed

        ConsultaPlaca v = new ConsultaPlaca();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModuloPlacasActionPerformed

    private void btnPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonasActionPerformed
        long numeroPersonas = a.contarPersonas();
        if (numeroPersonas >= 20) {
            int respuesta = JOptionPane.showConfirmDialog(null, "Ya hay más de 20 personas registradas en la base de datos. ¿Quiere volver a ingresarlas?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                a.insertarPersonas();
                JOptionPane.showMessageDialog(null, "Se insertaron 20 personas exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            a.insertarPersonas();
            JOptionPane.showMessageDialog(null, "Se insertaron 20 personas exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnPersonasActionPerformed

    private void btnModuloLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloLicenciaActionPerformed

        ConsultaLicencia v = new ConsultaLicencia();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModuloLicenciaActionPerformed

    private void btnModuloReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloReportesActionPerformed

        ConsultaPersonaTramite v = new ConsultaPersonaTramite();

        v.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnModuloReportesActionPerformed

    private void btnModuloConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloConsultasActionPerformed

        ConsultaPersona v = new ConsultaPersona();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModuloConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Aplicacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModuloConsultas;
    private javax.swing.JButton btnModuloLicencia;
    private javax.swing.JButton btnModuloPlacas;
    private javax.swing.JButton btnModuloReportes;
    private javax.swing.JButton btnPersonas;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
