/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import dominio.CostoTramite;
import dominio.Persona;
import implementaciones.LicenciaDAO;
import implementaciones.PersonaDAO;
import implementaciones.PlacaDAO;
import interfaces.ILicenciaDAO;
import interfaces.IPersonaDAO;
import interfaces.IPlacaDAO;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Logger;

/**
 *
 * @author Jesus
 */
public class CostosPlacas extends javax.swing.JFrame {

    private final IPersonaDAO a = new PersonaDAO();

    private final CostoTramite b = new CostoTramite();
    private final ILicenciaDAO c = new LicenciaDAO();
    private final IPlacaDAO d = new PlacaDAO();
    private String rfc;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CostosPlacas.class.getName());

    public CostosPlacas() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public CostosPlacas(String rfc) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        this.rfc = rfc;

        this.insertarDatosPersona();
        this.configurarTablaCostos();
        this.verificarPlacasExistentes();

        this.agregarManejadoresMouse();
    }

    private void insertarDatosPersona() {
        Persona persona = this.a.buscarPersonasRFC(rfc);
        if (persona != null) {
            String nombreCompleto = persona.getNombre() + " " + persona.getApellidoPaterno() + " " + persona.getApellidoMaterno();
            boolean licenciaVigente = c.validarLicenciaVigente(persona.getRfc());

            logger.info("Persona: " + nombreCompleto);
            logger.info("Licencia: " + (licenciaVigente ? "Vigente" : "No vigente"));
        } else {
            logger.warning("No se encontró persona con RFC: " + rfc);
        }
    }

    private void configurarTablaCostos() {

        jTable1.setModel(new DefaultTableModel(
                new Object[][]{},
                new String[]{"Tramite", "Costo"}
        ) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnIndex == 0 ? String.class : Double.class;
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.addRow(new Object[]{"Placas vehículo nuevo", b.placaNuevo});
        model.addRow(new Object[]{"Placas vehículo usado", b.placaUsado});
    }

    private void verificarPlacasExistentes() {
        Persona persona = a.buscarPersonasRFC(rfc);
        if (persona != null) {
            boolean tienePlacas = d.validaPersonaPlacas(persona);

            if (!tienePlacas) {

                lblVehiculoUsado.setEnabled(false);
                lblVehiculoUsado.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

                logger.info("Opción 'Vehículo usado' deshabilitada (no se encontraron placas previas).");
            } else {
                lblVehiculoUsado.setEnabled(true);
            }
        }
    }

    private void agregarManejadoresMouse() {

        MouseAdapter handCursorAdapter = new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent evt) {
                if (evt.getComponent().isEnabled()) {
                    setCursor(new Cursor(Cursor.HAND_CURSOR));
                }
            }

            @Override
            public void mouseExited(MouseEvent evt) {
                setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
        };

        lblVehiculoNuevo.addMouseListener(handCursorAdapter);
        lblVehiculoUsado.addMouseListener(handCursorAdapter);
        lblVentanaAtras.addMouseListener(handCursorAdapter);
    }

    private void lblAtrasMouseClicked(java.awt.event.MouseEvent evt) {
        ConsultaPlaca v = new ConsultaPlaca();
        v.setVisible(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVentanaAtras = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblVehiculoNuevo = new javax.swing.JLabel();
        lblVehiculoUsado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVentanaAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVentanaAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(lblVentanaAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 80));

        jTable1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tramite", "Costos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 970, 300));

        lblVehiculoNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVehiculoNuevoMouseClicked(evt);
            }
        });
        getContentPane().add(lblVehiculoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 270, 60));

        lblVehiculoUsado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVehiculoUsadoMouseClicked(evt);
            }
        });
        getContentPane().add(lblVehiculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 270, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/CostosPlacas.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblVentanaAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentanaAtrasMouseClicked
        ConsultaPlaca v = new ConsultaPlaca();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblVentanaAtrasMouseClicked

    private void lblVehiculoNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVehiculoNuevoMouseClicked
        RegistroAuto v = new RegistroAuto(rfc);
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblVehiculoNuevoMouseClicked

    private void lblVehiculoUsadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVehiculoUsadoMouseClicked

        if (lblVehiculoUsado.isEnabled()) {

            RenovacionPlacas v = new RenovacionPlacas(rfc);
            v.setVisible(true);
            dispose();
        } else {
            logger.warning("Intento de acceder a vehículo usado sin placas previas.");

        }
    }//GEN-LAST:event_lblVehiculoUsadoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblVehiculoNuevo;
    private javax.swing.JLabel lblVehiculoUsado;
    private javax.swing.JLabel lblVentanaAtras;
    // End of variables declaration//GEN-END:variables
}
